/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PINT_aliases.h"
#include "PINT.h"
#include "timer_clock.h"
#include "Timer.h"
#include "ISR_T_1.h"
#include "LCD.h"
#include "Llenar_aliases.h"
#include "Llenar.h"
#include "Vaciar_aliases.h"
#include "Vaciar.h"
#include "Timer2.h"
#include "Key_aliases.h"
#include "Key.h"
#include "IRS_key.h"
#include "P0_aliases.h"
#include "P0.h"
#include "ISR_T_2.h"
#include "timerclock.h"
#include "POUT_aliases.h"
#include "POUT.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

